version: '3'

tasks:
  dev:
    description: "Runs the webserver"
    dir: '{{.USER_WORKING_DIR}}'
    ignore_error: true
    env:
      ADMIN_TOKEN: test
    cmds:
      - (kubectl port-forward -n db deployments/redis-deploy 6379:6379 &)
      - air

  list:
    description: "Gets list of current subscriptions"
    cmds:
      - | 
        curl -H 'Authorization: {{.ADMIN_TOKEN}}' \
        -H "Content-Type: application/json" \
        http://localhost:3000/api/list

  check:
    description: "Runs go sec"
    cmds:
      - gosec ./...
